// src/routes/+page.svelte
<main>
  <h1>Welcome to my blog</h1>
  <p>An excerisice in writing.</p>
  <article>
    <h2>Learning to write or writing to learn?</h2>
    <p>This blog is a learning experience. For the longest time I have been meaning to improve my writing.
      By focusing on quantity and not quality I hope to become a better writier.</p>
    <p>When improving a skill most of the gain comes from the first 80% of progress, while most of the
      time goes into the last 20% percent. This blog is a homage to those first 80% or maybe not even those, we'll see.
      Either way I plan to improve this website one hastily writen blog post at a time. And hopefully I might just
      become a better writer in the process.</p>
  </article>
</main>

// routes/index.tsx
export default function Home() {
  return (
    <main>
      <h1 className="text-display2 mb-xs3">Welcome to my blog</h1>
      <p className="text-subheading-light mb-l">An excerisice in writing</p>
      <article className="mb-xl">
        <h2 className="text-titleB mb-xs">
          Learning to write or writing to learn?
        </h2>
        <p className="text-body-light mb-m">
          This blog is a learning experience. For the longest time I have been
          meaning to improve my writing. By focusing on quantity and not quality
          I hope to become a better writier.
        </p>
        <p className="text-body-light">
          When improving a skill most of the gain comes from the first 80% of
          progress, while most of the time goes into the last 20% percent. This
          blog is a homage to those first 80% or maybe not even those, we'll
          see. Either way I plan to improve this website one hastily writen blog
          post at a time. And hopefully I might just become a better writer in
          the process.
        </p>
      </article>
    </main>
  );
}
